name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    
    - name: Restore dependencies
      run: dotnet restore
      working-directory: Source

    - name: Version
      run: dotnet run --project GitTreeVersion -- version --directory-build-props
      working-directory: Source

    - name: Build
      run: dotnet build --no-restore
      working-directory: Source

    - name: Configure Git for tests
      run: |
        git config --global user.email "you@example.com"
        git config --global user.name "Your Name"
    
    - name: Test
      run: dotnet test --no-build --verbosity normal
      working-directory: Source

    - name: Pack
      run: dotnet pack --configuration Release
      working-directory: Source

    - name: NuGet push
      env:
        APIKEY: ${{ secrets.GitTreeVersionNuGetKey }}
      run: dotnet nuget push GitTreeVersion/bin/Release/GitTreeVersion.*.nupkg --api-key $APIKEY --source https://api.nuget.org/v3/index.json
      working-directory: Source
